version: '3.9'

services:
  db:
    image: postgres:15
    container_name: emp_postgres
    environment:
      POSTGRES_DB: empdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: emp_django
    command: sh -c "uv run python manage.py migrate && uv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=empdb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
